spring.application.name=decktracker

# Configuração direta para o Neon
spring.datasource.url=jdbc:postgresql://neondb_owner:npg_fNP2WeTwuyK7@ep-dry-dawn-acz4968l-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=SEU_USUARIO_AQUI
spring.datasource.password=SUA_SENHA_AQUI
spring.datasource.driver-class-name=org.postgresql.Driver

# Força o dialeto e a criação das tabelas
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Segurança
api.security.token.secret=${JWT_SECRET:ultra_super_senha_secreta_master_blaster_do_lontras}
